config/routes.rb
Rails.application.routes.draw do
  resources :duyurus
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'dashboard/index'
  devise_for :users
  get 'home/index'
  root 'home#index'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/duyuru.rb
class Duyuru < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, allow_blank: false
  	validates :body, presence: true, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  has_many :duyurus, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_worker

  def index
    
  end

  private

  def set_worker
      @user = current_user
  end
end

app/controllers/duyurus_controller.rb
class DuyurusController < InheritedResources::Base
  before_action :authenticate_user!, only: %i[index show new create edit update destroy ]
  before_action :set_duyuru, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[:show, :edit, :update, :destroy]

 



  

  private

    def set_duyuru
      @duyuru = Duyuru.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def duyuru_params
      params.require(:duyuru).permit(:user_id, :title, :body)
    end

    def correct_user
      @duyuru = current_user.duyurus.find_by(id: params[:id])
      redirect_to dashboard_index_path, notice: "Duyuruyu düzenlemeye yetkiniz yoktur" if @duyuru.nil?
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]


  # GET /duyurus/1/edit
  def edit
  end

  # PATCH/PUT /duyurus/1 or /duyurus/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to dashboard_index_path, notice: "Admin was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :muhasebe_mail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def resource_class
		User
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/duyurus_helper.rb
module DuyurusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/index.html.erb
<div class="container">
	<h5><%= current_user.name%> Dashboard</h5>
	<%# render "adminmenu"%>
	<div class="card">
  		<div class="card-body">
			<div class="row">
				<div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-2"><strong>Şirket Mail Adresi:</strong></div>
				<div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-2"><%= current_user.email %></div>
			</div>
			<%= turbo_frame_tag "user" do %>
			<div class="row">
				<div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-2"><strong>Şirket Adı: </strong></div>
				<div class="col-6 col-sm-6 col-md-4 col-lg-6 col-xl-6"><%= current_user.name%></div>
			</div>
			<div class="row">
				<div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-2"><strong>Muhasebe Mail Adresi: </strong></div>
				<div class="col-6 col-sm-6 col-md-4 col-lg-6 col-xl-6"><%= current_user.muhasebe_mail%></div>
			</div>
			 <%= link_to "Şirket Bilgileri Güncelleme", edit_user_path(@user), class:"btn btn-secondary btn-sm mt-2" %>
			<% end %>
			<%= link_to "Şifre Güncelleme", edit_user_registration_path, class:"btn btn-primary btn-sm mt-2" %>
		</div>
	</div>

	
</div>

app/views/duyurus/_form.html.erb
<%= form_with(model: duyuru) do |form| %>
  <% if duyuru.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(duyuru.errors.count, "error") %> prohibited this duyuru from being saved:</h2>

      <ul>
        <% duyuru.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.number_field :user_id, id: :duyuru_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  <div class="field">
    <%= form.label :"Duyuru başlığı:" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :"Duyuru:"%>
    <%= form.text_area :body , class:"form-control"%>
  </div>
  <div class="actions">
    <%= form.submit "Duyuru Oluştur", class:"btn btn-primary mt-1" %>
  </div>
<% end %>

app/views/duyurus/edit.html.erb
<h1>Editing Duyuru</h1>

<%= render 'form', duyuru: @duyuru %>

<%= link_to 'Show', @duyuru %> |
<%= link_to 'Back', duyurus_path %>

app/views/duyurus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Duyurus</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @duyurus.each do |duyuru| %>
      <tr>
        <td><%= duyuru.title %></td>
        <td><%= duyuru.body %></td>
        <td><%= link_to 'Show', duyuru %></td>
        <td><%= link_to 'Edit', edit_duyuru_path(duyuru) %></td>
        <td><%= link_to 'Destroy', duyuru, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duyuru', new_duyuru_path %>

app/views/duyurus/new.html.erb
<h1>New Duyuru</h1>

<%= render 'form', duyuru: @duyuru %>

<%= link_to 'Back', duyurus_path %>

app/views/duyurus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @duyuru.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @duyuru.body %>
</p>

<%= link_to 'Edit', edit_duyuru_path(@duyuru) %> |
<%= link_to 'Back', duyurus_path %>

app/views/home/_navbar.html.erb
<%# NAVBAR %>
<nav class="navbar navbar-expand-lg navbar-light m-0 p-0">
  <div class="container">
    <a class="navbar-brand mt-1" href="/"><%= image_tag "2.png", {height: 60} %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ms-auto mb-lg-0">
        <a class="nav-link" aria-current="page" href="/home/underconstruction">Hakkımızda</a>
        <a class="nav-link fw-bold" href="/home/underconstruction">Ücretlendirme</a>
        <% if user_signed_in? %>
        <div class="btn-group nav-link">
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hesabım
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Şirket Paneli", dashboard_index_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to "Güvenli çıkış", destroy_user_session_path, method: :delete,  data: { turbo: "false"} , class:"dropdown-item"%></li>
          </ul>
        </div>
        <% else %>
        <%= link_to "Şirket Girişi", new_user_session_path, class:"btn btn-outline-primary mx-2 rounded-pill px-2 mb-2 mb-lg-0" %>
        <%= link_to "Kullanıcı Girişi", new_user_session_path, class:"btn btn-outline-danger mx-2 rounded-pill px-2 mb-2 mb-lg-0" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<%# HERO %>
<div class="container">
    <div class="row g-2">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                <h1 class="display-4 mt-2 me-2" style="color: #c1502e;">
                    Personel taleplerinizi tek bir platformdan yönetin! </h1>
                    <% if user_signed_in? %>
                        <%= link_to "Şirket Paneli", dashboard_index_path, class:"btn btn-primary rounded-pill mt-5 px-5 py-2" %>
                    <% else %>
                    
                            <%= render "shared/signup" %>
                    <% end %>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 pt-5 ">
                <%= image_tag "07.jpg", {class: "img-fluid"} %>
            </div>
    </div>
</div>
<%# özellikler%>
<div class="text-center text-white" style="background-color: #f1ece5;">
    <div class="container py-4">
        <blockquote class="blockquote" style="color: #b85032;">Yüksek yazılım, bakım, kurulum ve danışman maliyetleri olmadan kolayca personel talep süreçlerinizi yönetin. Web tabanlı iş süreçleri ile güvenli ve ekonomik çözümlerden faydalanın. 
        </blockquote>
    </div>
</div>
<%# SERVICES %>
<div style="background-color: #f3f2f0;">
    <div class="container">
        <div class="row g-2">
            <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 mt-4 content-center" style="height: 200px;">
                <%= image_tag "03.png", {class: "img-fluid", style:"height: 200px"} %>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 mt-4">
                <h2>Masraf Listesi Süreçleri</h2>
                <p style="text-align: justify;">Çalışanlarınızı ve mail adreslerini tanımladıktan sonra, onay mekanizmalarını danışman desteği gerekmeden oluşturabiliyorsunuz. Masraf türlerini, projeleri ve proje bütçelerini kendiniz tanımlayabilirsiniz. Masraf listelerini TL, USD ve Euro cinsinden oluşturabilirsiniz. Masraf onaylarını masraf miktarına göre sınıflandırabilir ve onay aşamalarını değiştirebilirsiniz. Masraf listeslerine ilgili faturaların görüntülerini ekleyebilirsiniz. Fatura görüntüleriniz kriptolanmış şekilde Amazon serverlarında saklanır. Sizden başka kimse faturalarınıza ulaşamaz</p>
                <a class="btn btn-outline-dark" href="/home/underconstruction" role="button">Detaylı bilgi</a>
            </div>
            <div class="row g-2">
            <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 mt-3" style="height: 200px;">
                <%= image_tag "06.png", {class: "img-fluid", style:"height: 170px"} %>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 mt-3">
                <h2>Avans Talep Süreçleri</h2>
                <p style="text-align: justify;">Çalışanlarınızın maaş avans ve iş avansı süreçlerini de uygulamamız üzerinden oluşturabilirsiniz. İş avanslarını kendi belirleyeceğiniz avans türlerine tanımlayabilirsiniz. Tanımlayacağınız projeler ve proje bütçeleri ile avans taleplerini gruplandırabilirsiniz. Avans onay aşamalarını çalışana ve miktara göre özel olarak danışman desteği gerekmeksizin kendiniz yapabilirsiniz.</p>
                <a class="btn btn-outline-dark" href="/home/underconstruction" role="button">Detaylı bilgi</a>
            </div>
            <div class="row g-2">
            <div class="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 mt-3" style="height: 200px;">
                <%= image_tag "09.png", {class: "img-fluid", style:"height: 200px"} %>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 mt-3">
                <h2>Yıllık İzin ve Mazeret İzni Süreçleri</h2>
                <p style="text-align: justify;">Çalışanlarınızın izin haklarını sisteme tanımladıktan sonra izin onay süreçlerini kişiye özel tanımlayabilirsiniz. İzin talep formlarında izin isteme nedeni belirtilebilmektedir. Gerektiğinde sağlık raporu ve mazerete ilişkin belgeler de sisteme eklenebilmektedir. </p>
                <a class="btn btn-outline-dark" href="/home/underconstruction" role="button">Detaylı bilgi</a>
            </div>
        </div>
    </div>
</div>

<%# Footer %>

<footer class="border-top footer mt-auto py-3 text-start ">
  <div class="container">
    <span class="text-muted border-top-0">www.masraflistesi.com  |  D4 Software Solutions  |  2022  | <%= image_tag "2.png", {height: 50} %></span>
  </div>
</footer>

app/views/home/underconstruction.html.erb
<div class="container mt-5" style="max-width:800px; margin:auto;">
	<%= image_tag "under.png", {class: "img-fluid", style:""} %>
</div>

app/views/layouts/_flash.html.erb
<div data-controller="autohide">

	<div class=" container alert alert-warning alert-dismissible fade show" role="alert">
	      <% flash.each do |key, value| %>
			<% key %>
			<%= value %>
		<% end %>
	    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Masraflistesi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path "favml.png" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "home/navbar" %>
    <% if notice || alert %>
    <div class=" container alert alert-warning alert-dismissible fade show" role="alert">
      <%= notice %>
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_signup.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { data: { turbo: false} }) do |f| %>

<div class="py-4 col-12 col-sm-12 col-md-10 col-lg-8 col-xl-7">

  <div class="mb-3">
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control",placeholder:"E-posta" %>
  </div>

  <div class="mb-3">
    <% if @minimum_password_length %>
        <% @minimum_password_length %>
    <% end %>
    <%= f.password_field :password, autocomplete: "new-password", class:"form-control",placeholder:"Şifre"  %>
  </div>

  <div class="mb-3">
    <%= f.password_field :password_confirmation, autocomplete: "new-password" , class:"form-control",placeholder:"Şifre tekrar"  %>
  </div>

  <div>
    <%= f.submit "15 gün ücretsiz denemek için kaydol!", class:"btn btn-primary rounded-pill px-5 py-2 mt-2" %>
  </div>

</div>
<% end %>

app/views/users/_form.html.erb
<div>
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p><strong>Şirket Adı: </strong> <%= form.text_field :name, class:"form-control"%></p>
  <p><strong>Muhasebe Mail Adresi: </strong> <%= form.text_field :muhasebe_mail, class:"form-control" %></p>
  

  <div class="actions">
    <%= form.submit "Güncelle", class:"btn btn-outline-primary"%>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<%= turbo_frame_tag "user" do %>
	<%= render 'form', user: @user %>
<% end %>